# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
# follow xarray way https://github.com/pydata/xarray/blob/master/azure-pipelines.yml 

variables:
  pytest_extra_flags: ''
  allow_failure: false
  upstream_dev: false

jobs:

- job: Linux
  strategy:
    matrix:
      py38:
        conda_env: py38
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: ci/azure/unit-tests.yml

- job: MacOSX
  strategy:
    matrix:
      py38:
        conda_env: py38   		
  pool:
    vmImage: 'macOS-latest'
  steps:
  - template: ci/azure/unit-tests.yml
