name: pyPoseidon

channels:
  - conda-forge

dependencies:
  - python=2.7
  - pygrib=2.0.2
  - netCDF4=1.3.1
  - basemap=1.1.0
  - basemap-data-hires=1.1.0
  - python-eccodes=2.7.0
  - scipy=1.0.1
  - numpy=1.14.2
  - pyresample=1.8.3
  - cython=0.28.2
  - pandas=0.22.0
  - seaborn=0.8.1
  - urllib3=1.22
  - ffmpeg=3.4.2
  - cartopy=0.16.0
  - pydap=3.2.1
  - ecmwf-api-client=1.4
  - geopandas=0.3.0
  - xarray=0.10.3
  - holoviews=1.10.1
  - ioam::geoviews=1.4.3
  - bokeh=0.12.15 
  - bokeh::datashader=0.6.5
  - pip
  - pip:
  	- https://www.parallelpython.com/downloads/pp/pp-1.6.6.tar.gz  