name: pyPoseidon

channels:
  - conda-forge

dependencies:
  - dask
  - scipy
  - numpy
  - pyresample
  - pandas
  - netCDF4
  - seaborn
  - urllib3
  - pydap
  - geopandas
  - xarray
  - ipykernel
  - bokeh
  - ffmpeg
  - datashader
  - hvplot
  - holoviews
  - geoviews
  - rasterio
  - ipympl
  - tqdm
  - pynio
  - eccodes
  - mayavi
  - pip
  - pip:
    - cfgrib
#   - xesmf
