name: pyPoseidon

channels:
  - conda-forge

dependencies:
  - python=2.7
  - bunch
  - pygrib
  - tqdm
  - netCDF4
  - basemap
  - basemap-data-hires
  - python-eccodes
  - scipy
  - numpy
  - pyresample
  - cython
  - pandas
  - seaborn
  - urllib3
  - ffmpeg
  - cartopy
  - pydap
  - ecmwf-api-client
  - geopandas
  - xarray
  - cartopy
  - holoviews
  - ioam::geoviews 
  - bokeh::datashader  
