name: pyPoseidon

channels:
  - conda-forge

dependencies:
  - python=2.7
  - bunch
  - pygrib
  - tqdm
  - netCDF4
  - basemap
  - basemap-data-hires
  - python-eccodes
  - scipy
  - numpy
  - pyresample
  - pandas
  - seaborn
  - urllib3
  - ffmpeg
  - ipyleaflet
  - pydap
  - ecmwf-api-client
  - folium
  - fiona
  - geopandas
