name: pyPoseidon2

channels:
  - conda-forge

dependencies:
  - python=2.7
  - bunch
  - pygrib
  - tqdm
  - netCDF4
  - basemap
  - basemap-data-hires
  - python-eccodes
  - scipy
  - numpy
  - pyresample
  - cython
  - pandas
  - seaborn
  - urllib3
  - ffmpeg
  - ipyleaflet
  - cartopy
  - pydap
  - ecmwf-api-client
  - geopandas
  - xarray
  - cartopy
  - holoviews
  - ioam::geoviews
#mpi  
  - gcc
  - mpich
  - netcdf-fortran
  - ossuuid
  - autoconf
  - automake
  - libtool
  - defaults::m4
    
