name: pyPoseidon

channels:
  - conda-forge

dependencies:
  - python=2.7
  - pygrib
  - netCDF4
  - basemap
  - basemap-data-hires
  - python-eccodes
  - scipy
  - numpy
  - pyresample
  - cython
  - pandas
  - seaborn
  - urllib3
  - ffmpeg
  - cartopy
  - pydap
  - ecmwf-api-client
  - geopandas
  - xarray
  - holoviews
  - geoviews
  - bokeh
  - datashader
  - hvplot
  - ipympl
  - pynio
  - pip
  - pip:
    - https://www.parallelpython.com/downloads/pp/pp-1.6.6.tar.gz  
    - cfgrib
