name: pyPoseidon

channels:
  - conda-forge

dependencies:
  - python=3.8
  - mayavi
  - pyresample
# - pydap
  - dask
  - pygeos >=0.6
  - geoviews
  - geopandas>=0.10.1
  - rasterio
  - jigsaw=0.9.12
  - gmsh>=4.8.4
  - python-gmsh
  - hvplot
  - descartes
  - netCDF4
  - cfgrib <0.9.9
  - eccodes=2.19.1
  - libgfortran4
  - moviepy
  - imageio-ffmpeg
  - bump2version
  - colorlog
  - f90nml
  - pytest
  - pytest-cov
  - ipympl
  - zarr
  - mkdocs
  - black
  - pyvista
  - itkwidgets
  - mkdocstrings
  - pymdown-extensions
  - mkdocs-material
  - pip
  - pip:
    - "git+https://github.com/pydap/pydap.git@3f6aa190c59e3bbc6c834377a61579b20275ff69#egg=Pydap"
