name: pyPoseidon

channels:
  - conda-forge

dependencies:
  - python=3.7
  - dask
  - scipy
  - numpy
  - pyresample
  - pandas
  - netCDF4
  - seaborn
  - requests
  - pydap
  - geopandas
  - xarray
  - ipykernel
  - bokeh
  - ffmpeg
  - datashader
  - hvplot
  - holoviews
  - geoviews
  - rasterio
  - ipympl
  - tqdm
  - pynio
  - eccodes
  - mayavi
  - esmpy
  - sphinx
  - sphinx-gallery
  - sphinx_rtd_theme
  - pytest
  - cfgrib
  - jigsaw
  - pip
  - pip:    
    - xesmf
