name: Poseidon

channels:
  - conda-forge

dependencies:
  - python=2.7
  - bunch
  - pygrib
  - tqdm
  - netCDF4
  - basemap
  - python-eccodes
  - scipy
  - numpy
  - pyresample
  - pandas
  - seaborn
  - urllib3
  - ffmpeg
  