---

site_name: "pyPoseidon docs"
use_directory_urls: false

theme:
  name: "material"

nav:
  - Overview : "index.md"
  - Installation : "10_installation.md"
  - Usage : "20_usage.md"
  - API : "50_API.md"
  - References : "90_references.md"

markdown_extensions:
  - "admonition"
  - "codehilite"
  - "pymdownx.tilde"
  - "pymdownx.superfences"
  - toc:
      permalink: true

plugins:
  - "search"
  - "mkdocstrings":
