---

site_name: "pyPoseidon"
use_directory_urls: false
repo_url: "https://github.com/brey/pyPoseidon"

theme:
  name: "material"

nav:
  - Overview : "index.md"
  - Installation : "10_installation.md"
  - Structure : "20_structure.md"
  - User Guide : "30_usage.md"
  - API : "50_API.md"

markdown_extensions:
  - "admonition"
  - "codehilite"
  - "pymdownx.tilde"
  - "pymdownx.superfences"
  - toc:
      permalink: true

plugins:
  - "search"
  - "mkdocstrings":
