[tool.poetry]
name = "pyPoseidon"
version = "0.1.0"
description = ""
authors = ["Panos Mavrogiorgos <pmav99@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
cython = "*"
dask = "^2.6"
pandas = "^0.25.2"
requests = "^2.22"
geopandas = "^0.6.1"
xarray = "^0.14.0"
bokeh = "^1.3"
colorlog = "^4.0"
scipy = "^1.3"
netCDF4 = "^1.5"
matplotlib = "^3.1"
shapely = "^1.6"
pyresample = "^1.13.2"
pyproj = "2.0.2"
cartopy = "^0.17.0"
enum34 = { version = "^1.0", python = "<3.4" }
cytoolz = "^0.10.1"
pygeos = "^0.5"
cfgrib = "^0.9.7"
eccodes-python = "^0.9.3"

[tool.poetry.dev-dependencies]
sphinx = "^2.2"
sphinx_rtd_theme = "^0.4.3"
pytest = "^5.2"
pipdeptree = "^0.13.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
