channels:
  - conda-forge
  - gbrey
dependencies:
  - cartopy
  - cfgrib
  - colorlog
  - dask
  - delft3d4=65936*=mpi_mpich*
  - eccodes
  - f90nml
  - ffmpeg
  - gdal
  - geopandas
  - geos
  - gmsh>=4.9.3
  - jigsaw>=0.9.12
  - netCDF4
  - numpy
  - pandas
  - pip
  - proj
  - pschism=5.10*=mpi_mpich*
  - psutil
  - pydap>=3.3.0
  - pygeos
  - pyresample
  - python-gmsh
  - python=3.10
  - rasterio
  - requests
  - rioxarray
  - scipy
  - searvey
  - shapely
  - tqdm
  - xarray
