---

channels:
  - "conda-forge"
  - "gbrey"

dependencies:
  - "black<24.0"
  - "bump2version"
  - "conda-lock"
  - "conda-tree"
  - "ipykernel"
  - "pytest"
  - "pytest-cov"
  - "pytest-xdist"
  - "ruamel.yaml"
