---

channels:
  - "conda-forge"
  - "gbrey"

dependencies:
  - "black=21.12b0"
  - "bump2version"
  - "conda-lock"
  - "conda-tree"
  - "ipython"
  - "jupyterlab"
  - "pytest"
  - "pytest-cov"
  - "pytest-xdist"
