name: pyPoseidon

channels:
  - conda-forge
  - gbrey

dependencies:
  - python=3.8
  - mayavi
  - pyresample
  - pydap
  - dask
  - pygeos>=0.6
  - geoviews
  - geopandas
  - rasterio
  - jigsaw=0.9.12
  - seaborn
  - hvplot
  - descartes
  - netCDF4
  - cfgrib
  - moviepy
  - imageio-ffmpeg
  - bump2version
  - colorlog
  - f90nml
  - pytest
  - pytest-cov
  - ipympl
  - pschism
  - delft3d4
  - xorg-libxcursor
  - xorg-libxft
  - xorg-libxinerama
  - fltk
  - pip
  - pip:
    - gmsh
