name: pyPoseidon

channels:
  - conda-forge
  - gbrey

dependencies:
  - pyPoseidon
  - pschism
  - delft3d4
  - xorg-libxcursor
  - xorg-libxft
  - xorg-libxinerama
  - fltk
  - pip
  - pip:
    - gmsh
